/**
 * server/utils/ca-cards.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Current-affairs cards for the Nitro API routes.
 *
 * The cards come from content/data/ca/cards.json, generated by
 * scripts/generate-ca-export.ts during `predev` and `prebuild`.
 *
 * Do NOT reintroduce `queryCollection(event, ...)` here. Cloudflare Pages has no
 * runtime database, so a content query inside a server route throws and the
 * endpoint answers HTTP 500. Build-time JSON imports are the pattern that works
 * on the edge, exactly like content/data/study/pyqs.json.
 */
import cards from '~/content/data/ca/cards.json'

export interface CACard {
  id: string
  meta: Record<string, any>
}

export const CA_CARDS = cards as unknown as CACard[]

/** Real date the news happened, with fallbacks used across the CA UI. */
export function entryDate(e: CACard): string {
  return e?.meta?.event_date || e?.meta?.date || e?.meta?.published_at || ''
}

export function entryTime(e: CACard): number {
  const t = new Date(entryDate(e)).getTime()
  return Number.isNaN(t) ? 0 : t
}

/** "Today" means this calendar day in IST (UTC+5:30). */
export function istStartOfToday(now: Date): Date {
  const istOffset = 5.5 * 60 * 60 * 1000
  const istNow = new Date(now.getTime() + istOffset)
  return new Date(Date.UTC(
    istNow.getUTCFullYear(),
    istNow.getUTCMonth(),
    istNow.getUTCDate(),
  ) - istOffset)
}

export function windowCutoff(window: string, now: Date): Date | null {
  switch (window) {
    case '1D':
      return istStartOfToday(now)
    case '7D':
      return new Date(now.getTime() - 7 * 86400000)
    case '1M':
      return new Date(now.getTime() - 30 * 86400000)
    case '6M':
      return new Date(now.getTime() - 180 * 86400000)
    case '1Y':
      return new Date(now.getTime() - 365 * 86400000)
    default:
      return null // ALL or unrecognized
  }
}
